### ISSUE TITLE
Cool project, but.

### ISSUE THREAD

**Issue by Nexuzzzz** [billythegoat356/Plague#5]
Cool project, but won't stay FUD for long. Try implementing a polymorphic engine and some more anti-debug and anti-av functions :)

**Comment by billythegoat356** [comment]
Hi!
Not sure if it's even possible in Python. But yes i'm aware that it won't stay FUD for long. But for the moment it is!
Have a nice day!

**Comment by Nexuzzzz** [comment]
have a nice day too (sorry, i never check my email xd)

**Comment by billythegoat356** [comment]
Thanks!
